### ISSUE TITLE
[AG] I Assembleia-Geral

### ISSUE THREAD

**Issue by rafinhadufluxo** [ccuffs/Assembleia-geral#1]
Deliberações acerca da I Assembléia Geral Emergencial do curso de Ciência da Computação da Universidade Federal da Fronteira Sul Campus Chapecó.

O Centro Acadêmico de Ciência da Computação  no uso de suas atribuições legais, convocou em 5 de setembro de 2019 uma Assembléia Geral com seus associados tendo como pauta o posicionamento de todos perante a nomeação de Marcelo Recktenvald para o cargo de reitor e Gismael Perin para vice-reitor, terceiros colocados na consulta popular realizada em maio deste ano, onde foram escolhidos de maneira democrática Anderson Ribeiro para o cargo de reitor e Lísia Ferreira para o cargo de vice-reitora.
Diante do contexto e dos acontecimentos que afetam a comunidade, consultamos os associados do curso presentes na assembléia à respeito da continuidade das atividades acadêmicas e definimos por contagem de votos que os alunos estarão paralisados até o dia 9 de setembro de 2019. 
Além das decisões citadas acima também foram deliberadas as seguintes pautas que serão tratadas em uma nova assembléia que ocorrerá no dia 9 de setembro de 2019:

I. Nova consulta à respeito da continuidade das atividades do curso, na II Assembléia Geral gostaríamos que estivessem presentes um número maior de associados para que seja melhor discutido o posicionamento do curso.

II. Muitos associados têm apontado a ausência de atividades voltadas para o curso na universidade e fora dela, buscaremos na II Assembléia minimizar tal desconforto.

Chapecó, 05 de Setembro de 2019.

**Comment by annnyc** [comment]
Caros, conforme a deliberação da I Assembléia geral teremos uma segunda Assembléia na segunda-feira (09/09) e gostaríamos que preenchessem o seguinte formulário para abranger a maior parcela possível de discentes do curso, tendo em vista que na última assembléia nem todos puderam ser ouvidos devido ao horário e seu caráter emergencial.
https://forms.gle/sirku7rvvbCqtfvb6
